from ms_sample_list_creator.implementations.result import Result
from ms_sample_list_creator.structure import Batch, DirectusCredentials, Method

def get_batches() -> dict[str, int]: ...
def get_instruments() -> dict[str, str]: ...
def test_credentials(credentials: DirectusCredentials) -> Result[str, str]: ...
def test_batch(batch: Batch, token: str) -> Result[Batch, str]: ...
def get_methods(method: str, token: str) -> list[Method]: ...
