from ms_sample_list_creator.implementations.result import Result
from ms_sample_list_creator.structure import Batch, Instrument, Method, SampleContainer, SampleData

def get_batches() -> Result[list[Batch], str]: ...
def get_instruments() -> Result[list[Instrument], str]: ...
def test_batch(batch: Batch) -> Result[Batch, str]: ...
def get_methods(methods_list: list[str]) -> Result[list[Method], str]: ...
def get_aliquot(aliquot_id: str) -> Result[SampleContainer, str]: ...
def insert_ms_sample(timestamp: str, operator: str, sample: SampleData) -> Result[bool, str]: ...
