from ms_sample_list_creator.implementations.result import Result
from ms_sample_list_creator.structure import Batch, DirectusCredentials, Instrument, Method, SampleContainer, SampleData

def get_batches() -> Result[list[Batch], str]: ...
def get_instruments() -> Result[list[Instrument], str]: ...
def login_to_directus(credentials: DirectusCredentials) -> Result[str, str]: ...
def test_batch(batch: Batch, token: str) -> Result[Batch, str]: ...
def get_methods(methods_list: list[str], token: str) -> Result[list[Method], str]: ...
def get_aliquot(aliquot_id: str) -> Result[SampleContainer, str]: ...
def insert_ms_sample(token: str, timestamp: str, operator: str, sample: SampleData) -> Result[bool, str]: ...
